"use client";

import React, { useEffect, useMemo, useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useApp } from "@/app/context/AppContext";
import { Product, CategoryOption } from "@/types/product";
import api from "@/utils/api";
import Loader from "@/components/Loader";
import { Plus, Search, Edit3, Trash2, Download, X } from "lucide-react";
import toast from "react-hot-toast";


function AdminProductsContent() {
  const { products, addProduct, updateProduct, deleteProduct, bulkDeleteProducts, bulkUpdateProducts, productsLoading } = useApp();
  const searchParams = useSearchParams();
  const router = useRouter();

  const [searchQuery, setSearchQuery] = useState("");
  const [filterBrand, setFilterBrand] = useState("All");
  const [categoryGroups, setCategoryGroups] = useState<CategoryOption[]>([]);

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);

  const [formName, setFormName] = useState("");
  const [formBrand, setFormBrand] = useState("");
  const [formCategory, setFormCategory] = useState<string[]>([]);
  const [formSubCategory, setFormSubCategory] = useState<string[]>([]);
  const [formGender, setFormGender] = useState<string[]>([]);
  const [formSport, setFormSport] = useState<string[]>([]);
  const [formMRP, setFormMRP] = useState(100);
  const [formSellingPrice, setFormSellingPrice] = useState(90);
  const [formTax, setFormTax] = useState(18);
  const [formSKU, setFormSKU] = useState("");
  const [formStock, setFormStock] = useState(10);
  const [formMinStock, setFormMinStock] = useState(3);
  const [formColors, setFormColors] = useState("Black, White");
  const [formSizes, setFormSizes] = useState("8, 9, 10");
  const [formThumbnail, setFormThumbnail] = useState("");
  const [formThumbnailFile, setFormThumbnailFile] = useState<File | null>(null);
  const [formDescription, setFormDescription] = useState("");
  const [formShortDescription, setFormShortDescription] = useState("");

  useEffect(() => {
    const loadCategories = async () => {
      try {
        const data = await api.get("/categories");
        setCategoryGroups(Array.isArray(data) ? data : []);
      } catch {
        setCategoryGroups([]);
      }
    };
    loadCategories();
  }, []);

  useEffect(() => {
    if (searchParams.get("action") === "new") {
      handleOpenAddForm();
      router.push("/admin/products");
    }
  }, [searchParams, router]);

  const selectedCategories = useMemo(
    () => categoryGroups.filter((category) => formCategory.includes(category.name)),
    [categoryGroups, formCategory]
  );

  const categoryOptions = useMemo(() => {
    return categoryGroups.map((category) => category.name);
  }, [categoryGroups]);

  const subcategoryOptions = useMemo(() => {
    if (selectedCategories.length === 0) return [];
    const allSubs: { id: string; name: string }[] = [];
    const seen = new Set<string>();
    for (const cat of selectedCategories) {
      for (const sub of cat.subcategories) {
        if (!seen.has(sub.name)) {
          seen.add(sub.name);
          allSubs.push(sub);
        }
      }
    }
    return allSubs;
  }, [selectedCategories]);

  const uniqueBrands = useMemo(() => ["All", ...Array.from(new Set(products.map((product) => product.brand)))], [products]);

  const filteredProducts = useMemo(
    () => products.filter((product) => {
      const matchSearch = product.name.toLowerCase().includes(searchQuery.toLowerCase()) || product.sku.toLowerCase().includes(searchQuery.toLowerCase());
      const matchBrand = filterBrand === "All" || product.brand === filterBrand;
      return matchSearch && matchBrand;
    }),
    [products, searchQuery, filterBrand]
  );

  const handleOpenAddForm = () => {
    setEditingProduct(null);
    setFormName("");
    setFormBrand("");
    setFormCategory([]);
    setFormSubCategory([]);
    setFormGender([]);
    setFormSport([]);
    setFormMRP(100);
    setFormSellingPrice(90);
    setFormTax(18);
    setFormSKU(""); // SKU auto-generated by backend
    setFormStock(15);
    setFormMinStock(3);
    setFormColors("Black, White, Blue");
    setFormSizes("8, 9, 10");
    setFormThumbnail("");
    setFormThumbnailFile(null);
    setFormDescription("");
    setFormShortDescription("");
    setIsFormOpen(true);
  };

  const handleOpenEditForm = (product: Product) => {
    setEditingProduct(product);
    setFormName(product.name);
    setFormBrand(product.brand);
    setFormCategory(product.category ? [product.category] : []);
    setFormSubCategory(product.subCategory ? [product.subCategory] : []);
    setFormGender(product.gender ? [product.gender] : []);
    setFormSport(product.sportType ? [product.sportType] : []);
    setFormMRP(product.mrp);
    setFormSellingPrice(product.sellingPrice);
    setFormTax(product.tax);
    setFormSKU(product.sku);
    setFormStock(product.stock);
    setFormMinStock(product.minStock);
    setFormColors(product.colors.join(", "));
    setFormSizes(product.sizes.join(", "));
    setFormThumbnail(product.thumbnail);
    setFormThumbnailFile(null);
    setFormDescription(product.description);
    setFormShortDescription(product.shortDescription);
    setIsFormOpen(true);
  };

  const handleCategoryChange = (value: string) => {
    setFormCategory((prev) => {
      const next = prev.includes(value) ? prev.filter((c) => c !== value) : [...prev, value];
      // Clear subcategories that don't belong to any selected category
      return next;
    });
    setFormSubCategory([]);
  };

  const handleFormSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!formCategory.length || !formSubCategory.length || !formGender.length || !formSport.length) return;

    const colorsArray = formColors.split(",").map((color) => color.trim()).filter(Boolean);
    const sizesArray = formSizes.split(",").map((size) => size.trim()).filter(Boolean);
    const discountPercentage = Math.round(((formMRP - formSellingPrice) / formMRP) * 100);

    let thumbnailValue = formThumbnail;
    if (formThumbnailFile) {
      thumbnailValue = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result || ""));
        reader.onerror = () => reject(new Error("Failed to read image file"));
        reader.readAsDataURL(formThumbnailFile);
      });
    }

    const productPayload: any = {
      name: formName,
      brand: formBrand,
      category: formCategory[0],
      subCategory: formSubCategory[0],
      gender: formGender[0] as Product["gender"],
      sportType: formSport[0],
      mrp: Number(formMRP),
      sellingPrice: Number(formSellingPrice),
      discount: Math.max(0, discountPercentage),
      tax: Number(formTax),
      ...(editingProduct ? { sku: formSKU } : {}), // only send sku on edit
      stock: Number(formStock),
      minStock: Number(formMinStock),
      colors: colorsArray,
      sizes: sizesArray,
      thumbnail: thumbnailValue,
      gallery: [thumbnailValue],
      description: formDescription,
      shortDescription: formShortDescription,
      metaTitle: "",
      metaDescription: "",
      keywords: "",
    };

    try {
      if (editingProduct) {
        const res = await updateProduct(editingProduct.id, productPayload);
        if (res.error) {
          toast.error(res.payload || "Failed to update product.");
        } else {
          toast.success(`"${formName}" updated successfully!`);
          setIsFormOpen(false);
        }
      } else {
        const res = await addProduct(productPayload);
        if (res.error) {
          toast.error(res.payload || "Failed to add product.");
        } else {
          toast.success(`"${formName}" added to catalog!`);
          setIsFormOpen(false);
        }
      }
    } catch (err: any) {
      toast.error(err.message || "An unexpected error occurred.");
    }
  };

  const handleBulkDelete = () => {
    if (confirm(`Are you sure you want to delete ${selectedIds.length} products?`)) {
      bulkDeleteProducts(selectedIds);
      setSelectedIds([]);
    }
  };

  const handleBulkOutofStock = () => {
    bulkUpdateProducts(selectedIds, { stock: 0 });
    setSelectedIds([]);
  };

  const toggleSelectId = (id: string) => {
    setSelectedIds((prev) => (prev.includes(id) ? prev.filter((value) => value !== id) : [...prev, id]));
  };

  const toggleSelectAll = () => {
    setSelectedIds(selectedIds.length === filteredProducts.length ? [] : filteredProducts.map((product) => product.id));
  };

  const handleExportCSV = () => {
    const headers = "ID,Name,Brand,SKU,MRP,SellingPrice,Stock,Category,Sport\n";
    const rows = filteredProducts
      .map((product) => `${product.id},"${product.name.replace(/"/g, '""')}",${product.brand},${product.sku},${product.mrp},${product.sellingPrice},${product.stock},${product.category},${product.sportType}`)
      .join("\n");

    const blob = new Blob([headers + rows], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "athletica_inventory.csv";
    link.click();
  };

  if (productsLoading) return <Loader />;

  return (
    <div className="flex flex-col gap-6">
      <section className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-gray-300 pb-5">
        <div>
          <h1 className="text-2xl font-black uppercase text-black">Products Catalog</h1>
          <p className="text-xs text-zinc-400 font-semibold uppercase mt-0.5">Maintain items inventories, listings, and pricing margins</p>
        </div>
        <div className="flex flex-wrap gap-3">
          <button onClick={handleExportCSV} className="border border-gray-300 bg-white hover:bg-zinc-50 px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider flex items-center gap-2">
            <Download size={13} /> Export CSV
          </button>
          <button onClick={handleOpenAddForm} className="bg-black hover:bg-black-400 text-white px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider flex items-center gap-2">
            <Plus size={13} /> Add Product
          </button>
        </div>
      </section>

      <section className="flex flex-col sm:flex-row gap-4 justify-between items-center bg-white border border-gray-300 p-4 rounded-2xl">
        <div className="relative w-full sm:w-80">
          <input type="text" placeholder="Search Name or SKU..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 pl-10 text-xs font-semibold text-black focus:border-black focus:bg-white focus:outline-none" />
          <Search className="absolute left-3.5 top-2.5 text-zinc-400" size={14} />
        </div>
        <div className="flex items-center gap-3 w-full sm:w-auto justify-end text-xs font-bold text-zinc-400 uppercase">
          <span>Brand:</span>
          <select value={filterBrand} onChange={(e) => setFilterBrand(e.target.value)} className="border border-gray-300 rounded-xl bg-zinc-50 px-3 py-2 text-black font-bold focus:outline-none">
            {uniqueBrands.map((brand) => <option key={brand} value={brand}>{brand}</option>)}
          </select>
        </div>
      </section>

      {selectedIds.length > 0 && (
        <section className="bg-zinc-100 border border-gray-300 p-4 rounded-2xl flex items-center justify-between text-xs">
          <span className="font-extrabold text-zinc-700">Selected <span className="text-accent font-black">{selectedIds.length}</span> Products</span>
          <div className="flex gap-3">
            <button onClick={handleBulkOutofStock} className="border border-gray-300 hover:bg-zinc-200 px-3 py-1.5 rounded-lg font-bold uppercase text-[10px] text-zinc-700">Mark Out of Stock</button>
            <button onClick={handleBulkDelete} className="bg-red-600 hover:bg-red-700 text-white px-3 py-1.5 rounded-lg font-bold uppercase text-[10px]">Delete Selected</button>
          </div>
        </section>
      )}

      <section className="bg-white border border-gray-300 rounded-3xl overflow-hidden">
        <div className="overflow-x-auto text-xs text-left">
          {filteredProducts.length > 0 ? (
            <table className="w-full border-collapse">
              <thead>
                <tr className="border-b border-gray-300 text-zinc-400 font-bold uppercase text-[10px]">
                  <th className="p-4 w-12 text-center">
                    <input type="checkbox" checked={selectedIds.length === filteredProducts.length && filteredProducts.length > 0} onChange={toggleSelectAll} className="rounded border-zinc-300 text-accent w-4 h-4" />
                  </th>
                  <th className="p-4">Product Info</th>
                  <th className="p-4">SKU</th>
                  <th className="p-4">MRP / Price</th>
                  <th className="p-4">Stock</th>
                  <th className="p-4">Classification</th>
                  <th className="p-4 text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredProducts.map((product) => {
                  const isLow = product.stock <= product.minStock && product.stock > 0;
                  const isOOS = product.stock === 0;
                  const checked = selectedIds.includes(product.id);

                  return (
                    <tr key={product.id} className={`border-b border-gray-100 last:border-none hover:bg-zinc-50/50 ${checked ? "bg-blue-50/10" : ""}`}>
                      <td className="p-4 text-center">
                        <input type="checkbox" checked={checked} onChange={() => toggleSelectId(product.id)} className="rounded border-zinc-300 text-accent w-4 h-4" />
                      </td>
                      <td className="p-4">
                        <div className="flex items-center gap-3">
                          <img src={product.thumbnail} className="w-10 h-10 object-cover rounded-lg border border-gray-200" alt="" />
                          <div>
                            <p className="font-extrabold text-black text-sm line-clamp-1">{product.name}</p>
                            <p className="text-[10px] text-zinc-400 font-bold uppercase">{product.brand}</p>
                          </div>
                        </div>
                      </td>
                      <td className="p-4 font-mono font-bold text-zinc-500">{product.sku}</td>
                      <td className="p-4 font-semibold">
                        <span className="text-black font-extrabold">₹{product.sellingPrice}</span>
                        {product.mrp > product.sellingPrice && <span className="text-zinc-400 line-through ml-1.5">₹{product.mrp}</span>}
                      </td>
                      <td className="p-4">
                        {isOOS ? (
                          <span className="px-2 py-0.5 rounded bg-red-50 text-red-700 font-bold uppercase text-[9px]">Out Of Stock</span>
                        ) : isLow ? (
                          <span className="px-2 py-0.5 rounded bg-amber-50 text-amber-700 font-bold uppercase text-[9px]">Low ({product.stock})</span>
                        ) : (
                          <span className="font-extrabold text-green-600">{product.stock} Units</span>
                        )}
                      </td>
                      <td className="p-4 font-bold text-zinc-500 uppercase text-[10px]">{product.category} • {product.subCategory}</td>
                      <td className="p-4 text-center">
                        <div className="flex justify-center items-center gap-2">
                          <button onClick={() => handleOpenEditForm(product)} className="p-1.5 text-zinc-500 hover:text-black border border-gray-300 rounded-lg hover:border-black transition-all" title="Edit Product"><Edit3 size={12} /></button>
                          <button onClick={() => { if (confirm("Delete this product?")) deleteProduct(product.id); }} className="p-1.5 text-zinc-400 hover:text-red-600 border border-gray-300 rounded-lg hover:border-red-200 transition-all" title="Delete Product"><Trash2 size={12} /></button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          ) : (
            <div className="text-center py-20 italic text-zinc-400">No products match search criteria.</div>
          )}
        </div>
      </section>

      {isFormOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="w-full max-w-2xl max-h-[90vh] bg-white rounded-2xl overflow-y-auto flex flex-col gap-6 p-6 shadow-2xl">
            <div className="flex items-center justify-between border-b border-gray-300 pb-4">
              <h3 className="font-black text-sm uppercase tracking-wider">{editingProduct ? `Edit Product: ${editingProduct.sku}` : "Add New Sportswear Item"}</h3>
              <button onClick={() => setIsFormOpen(false)} className="p-1.5 text-zinc-400 hover:text-black" title="Close Form"><X size={20} /></button>
            </div>

            <form onSubmit={handleFormSubmit} className="flex flex-col gap-6 text-xs text-left">
              <div className="flex flex-col gap-3">
                <h4 className="font-black text-[10px] text-black uppercase tracking-widest border-b border-gray-300 pb-1.5">1. Basic Information</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="sm:col-span-2">
                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Product Name</label>
                    <input type="text" required value={formName} onChange={(e) => setFormName(e.target.value)} placeholder="e.g. Vaporfly Next% Running Shoes" className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" />
                  </div>
                  <div className="sm:col-span-2">
                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Short Description</label>
                    <input type="text" required value={formShortDescription} onChange={(e) => setFormShortDescription(e.target.value)} placeholder="A short punchy line for previews." className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" />
                  </div>
                  <div className="sm:col-span-2">
                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Detailed Description</label>
                    <textarea required rows={4} value={formDescription} onChange={(e) => setFormDescription(e.target.value)} placeholder="Explain features, fit specifications, technology stack details." className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" />
                  </div>
                </div>
              </div>

              <div className="flex flex-col gap-3">
                <h4 className="font-black text-[10px] text-black uppercase tracking-widest border-b border-gray-300 pb-1.5">2. Pricing & Inventory</h4>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                  <div><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">MRP (₹)</label><input type="number" required min="1" value={formMRP} onChange={(e) => setFormMRP(Number(e.target.value))} className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" /></div>
                  <div><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Selling Price (₹)</label><input type="number" required min="1" value={formSellingPrice} onChange={(e) => setFormSellingPrice(Number(e.target.value))} className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" /></div>
                  <div><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Tax (%)</label><input type="number" required value={formTax} onChange={(e) => setFormTax(Number(e.target.value))} className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" /></div>
                  {editingProduct && (
                    <div><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">SKU Code</label><input type="text" readOnly value={formSKU} className="w-full rounded-xl border border-gray-200 bg-gray-100 px-4 py-2 text-xs font-semibold text-zinc-500 cursor-not-allowed" /></div>
                  )}
                  <div><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Stock Level</label><input type="number" required value={formStock} onChange={(e) => setFormStock(Number(e.target.value))} className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" /></div>
                  <div><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Min Stock Warning</label><input type="number" required value={formMinStock} onChange={(e) => setFormMinStock(Number(e.target.value))} className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" /></div>
                </div>
              </div>

              <div className="flex flex-col gap-3">
                <h4 className="font-black text-[10px] text-black uppercase tracking-widest border-b border-gray-300 pb-1.5">3. Classifications & Variants</h4>

                {/* Category */}
                <div>
                  <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-2">Category</label>
                  <div className="flex flex-wrap gap-2">
                    {(categoryOptions.length > 0 ? categoryOptions : ["Men"]).map((category) => (
                      <label key={category} className={`flex items-center gap-1.5 border rounded-lg px-3 py-1.5 text-[11px] font-semibold cursor-pointer transition-all ${formCategory.includes(category) ? "bg-black text-white border-black" : "border-gray-300 text-zinc-700 hover:border-black bg-zinc-50"}`}>
                        <input type="checkbox" checked={formCategory.includes(category)} onChange={() => handleCategoryChange(category)} className="h-3.5 w-3.5 accent-black border-zinc-300" />
                        {category}
                      </label>
                    ))}
                  </div>
                </div>

                {/* Subcategory */}
                <div>
                  <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-2">Subcategory</label>
                  {subcategoryOptions.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {subcategoryOptions.map((subcategory) => (
                        <label key={subcategory.id} className={`flex items-center gap-1.5 border rounded-lg px-3 py-1.5 text-[11px] font-semibold cursor-pointer transition-all ${formSubCategory.includes(subcategory.name) ? "bg-black text-white border-black" : "border-gray-300 text-zinc-700 hover:border-black bg-zinc-50"}`}>
                          <input type="checkbox" checked={formSubCategory.includes(subcategory.name)} onChange={() => setFormSubCategory((prev) => prev.includes(subcategory.name) ? prev.filter((s) => s !== subcategory.name) : [...prev, subcategory.name])} className="h-3.5 w-3.5 accent-black border-zinc-300" />
                          {subcategory.name}
                        </label>
                      ))}
                    </div>
                  ) : (
                    <p className="text-[10px] text-zinc-400 italic">Select a category to see subcategories</p>
                  )}
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {/* Gender */}
                  <div>
                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-2">Gender</label>
                    <div className="flex flex-wrap gap-2">
                      {["Men", "Women", "Kids", "Unisex"].map((gender) => (
                        <label key={gender} className={`flex items-center gap-1.5 border rounded-lg px-3 py-1.5 text-[11px] font-semibold cursor-pointer transition-all ${formGender.includes(gender) ? "bg-black text-white border-black" : "border-gray-300 text-zinc-700 hover:border-black bg-zinc-50"}`}>
                          <input type="checkbox" checked={formGender.includes(gender)} onChange={() => setFormGender((prev) => prev.includes(gender) ? prev.filter((g) => g !== gender) : [...prev, gender])} className="h-3.5 w-3.5 accent-black border-zinc-300" />
                          {gender}
                        </label>
                      ))}
                    </div>
                  </div>

                  {/* Sport Type */}
                  <div>
                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-2">Sport Type</label>
                    <div className="flex flex-wrap gap-2">
                      {["Running", "Training", "Football", "Basketball", "Cricket", "Gym", "All"].map((sport) => (
                        <label key={sport} className={`flex items-center gap-1.5 border rounded-lg px-3 py-1.5 text-[11px] font-semibold cursor-pointer transition-all ${formSport.includes(sport) ? "bg-black text-white border-black" : "border-gray-300 text-zinc-700 hover:border-black bg-zinc-50"}`}>
                          <input type="checkbox" checked={formSport.includes(sport)} onChange={() => setFormSport((prev) => prev.includes(sport) ? prev.filter((s) => s !== sport) : [...prev, sport])} className="h-3.5 w-3.5 accent-black border-zinc-300" />
                          {sport}
                        </label>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Brand, Colors, Sizes */}
                <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
                  <div className="col-span-2 sm:col-span-1"><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Brand</label><input type="text" required value={formBrand} onChange={(e) => setFormBrand(e.target.value)} placeholder="Nike, Puma, etc." className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-black focus:outline-none" /></div>
                  <div className="col-span-2 sm:col-span-2"><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Colors (Comma separated)</label><input type="text" required value={formColors} onChange={(e) => setFormColors(e.target.value)} placeholder="Black, White, Blue" className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-black focus:outline-none" /></div>
                  <div className="col-span-2 sm:col-span-2"><label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Sizes (Comma separated)</label><input type="text" required value={formSizes} onChange={(e) => setFormSizes(e.target.value)} placeholder="8, 9, 10" className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-black focus:outline-none" /></div>
                </div>
              </div>

              <div className="flex flex-col gap-3">
                <h4 className="font-black text-[10px] text-black uppercase tracking-widest border-b border-gray-300 pb-1.5">4. Product Images</h4>
                {editingProduct && formThumbnail && !formThumbnailFile && (
                  <div>
                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Current Thumbnail</label>
                    <img src={formThumbnail} alt="Current thumbnail" className="w-20 h-20 object-cover rounded-xl border border-gray-200" />
                  </div>
                )}
                {formThumbnailFile && (
                  <div>
                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">New Image Preview</label>
                    <img src={URL.createObjectURL(formThumbnailFile)} alt="New thumbnail preview" className="w-20 h-20 object-cover rounded-xl border border-gray-200" />
                  </div>
                )}
                <div>
                  <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Thumbnail / Main Image{editingProduct ? " (leave empty to keep current)" : ""}</label>
                  <input type="file" accept="image/*" required={!editingProduct} onChange={(e) => setFormThumbnailFile(e.target.files?.[0] || null)} className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 focus:outline-none" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Or Paste Image URL</label>
                  <input type="text" value={formThumbnailFile ? "" : formThumbnail} onChange={(e) => { setFormThumbnail(e.target.value); setFormThumbnailFile(null); }} placeholder="https://example.com/image.jpg" className="w-full rounded-xl border border-gray-300 bg-zinc-50 px-4 py-2 text-xs font-semibold focus:outline-none" />
                </div>
              </div>

              <div className="border-t border-gray-300 pt-6 flex gap-4">
                <button type="button" onClick={() => setIsFormOpen(false)} className="flex-1 border border-gray-300 text-zinc-500 py-3.5 rounded-xl font-bold uppercase text-xs hover:bg-zinc-50">Cancel</button>
                <button type="submit" className="flex-1 bg-black hover:bg-black-400 text-white py-3.5 rounded-xl font-bold uppercase text-xs">{editingProduct ? "Save Changes" : "Create Product"}</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default function AdminProductsPage() {
  return (
    <Suspense fallback={<div className="flex h-[50vh] items-center justify-center bg-white"><div className="h-8 w-8 animate-spin rounded-full border-4 border-solid border-accent border-t-transparent" /></div>}>
      <AdminProductsContent />
    </Suspense>
  );
}
